// +build debug
// Code generated by go-bindata.
// sources:
// data/datasets/AF001EW/2016/1/1.json
// data/datasets/AF001EW/2016/1/dimensions.json
// data/datasets/AF001EW/2016/versions.json
// data/datasets/AF001EW/editions.json
// data/datasets/CPI15/2017/1/1.json
// data/datasets/CPI15/2017/1/dimensions.json
// data/datasets/CPI15/2017/versions.json
// data/datasets/CPI15/editions.json
// data/datasets/legacy/AF001EW.json
// data/datasets/legacy/CPI15.json
// data/datasets.json
// data/hierarchies/CI_000641.json
// data/hierarchies/TIME_001.json
// data/hierarchies.json
// DO NOT EDIT!

package stub

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// dataDatasetsAf001ew201611Json reads file data from disk. It returns an error on failure.
func dataDatasetsAf001ew201611Json() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/AF001EW/2016/1/1.json"
	name := "data/datasets/AF001EW/2016/1/1.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsAf001ew20161DimensionsJson reads file data from disk. It returns an error on failure.
func dataDatasetsAf001ew20161DimensionsJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/AF001EW/2016/1/dimensions.json"
	name := "data/datasets/AF001EW/2016/1/dimensions.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsAf001ew2016VersionsJson reads file data from disk. It returns an error on failure.
func dataDatasetsAf001ew2016VersionsJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/AF001EW/2016/versions.json"
	name := "data/datasets/AF001EW/2016/versions.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsAf001ewEditionsJson reads file data from disk. It returns an error on failure.
func dataDatasetsAf001ewEditionsJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/AF001EW/editions.json"
	name := "data/datasets/AF001EW/editions.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsCpi15201711Json reads file data from disk. It returns an error on failure.
func dataDatasetsCpi15201711Json() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/CPI15/2017/1/1.json"
	name := "data/datasets/CPI15/2017/1/1.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsCpi1520171DimensionsJson reads file data from disk. It returns an error on failure.
func dataDatasetsCpi1520171DimensionsJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/CPI15/2017/1/dimensions.json"
	name := "data/datasets/CPI15/2017/1/dimensions.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsCpi152017VersionsJson reads file data from disk. It returns an error on failure.
func dataDatasetsCpi152017VersionsJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/CPI15/2017/versions.json"
	name := "data/datasets/CPI15/2017/versions.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsCpi15EditionsJson reads file data from disk. It returns an error on failure.
func dataDatasetsCpi15EditionsJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/CPI15/editions.json"
	name := "data/datasets/CPI15/editions.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsLegacyAf001ewJson reads file data from disk. It returns an error on failure.
func dataDatasetsLegacyAf001ewJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/legacy/AF001EW.json"
	name := "data/datasets/legacy/AF001EW.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsLegacyCpi15Json reads file data from disk. It returns an error on failure.
func dataDatasetsLegacyCpi15Json() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets/legacy/CPI15.json"
	name := "data/datasets/legacy/CPI15.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataDatasetsJson reads file data from disk. It returns an error on failure.
func dataDatasetsJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/datasets.json"
	name := "data/datasets.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataHierarchiesCi_000641Json reads file data from disk. It returns an error on failure.
func dataHierarchiesCi_000641Json() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/hierarchies/CI_000641.json"
	name := "data/hierarchies/CI_000641.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataHierarchiesTime_001Json reads file data from disk. It returns an error on failure.
func dataHierarchiesTime_001Json() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/hierarchies/TIME_001.json"
	name := "data/hierarchies/TIME_001.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataHierarchiesJson reads file data from disk. It returns an error on failure.
func dataHierarchiesJson() (*asset, error) {
	path := "/Users/mo/ons/go/src/github.com/ONSdigital/dp-dd-api-stub/stub/data/hierarchies.json"
	name := "data/hierarchies.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/datasets/AF001EW/2016/1/1.json": dataDatasetsAf001ew201611Json,
	"data/datasets/AF001EW/2016/1/dimensions.json": dataDatasetsAf001ew20161DimensionsJson,
	"data/datasets/AF001EW/2016/versions.json": dataDatasetsAf001ew2016VersionsJson,
	"data/datasets/AF001EW/editions.json": dataDatasetsAf001ewEditionsJson,
	"data/datasets/CPI15/2017/1/1.json": dataDatasetsCpi15201711Json,
	"data/datasets/CPI15/2017/1/dimensions.json": dataDatasetsCpi1520171DimensionsJson,
	"data/datasets/CPI15/2017/versions.json": dataDatasetsCpi152017VersionsJson,
	"data/datasets/CPI15/editions.json": dataDatasetsCpi15EditionsJson,
	"data/datasets/legacy/AF001EW.json": dataDatasetsLegacyAf001ewJson,
	"data/datasets/legacy/CPI15.json": dataDatasetsLegacyCpi15Json,
	"data/datasets.json": dataDatasetsJson,
	"data/hierarchies/CI_000641.json": dataHierarchiesCi_000641Json,
	"data/hierarchies/TIME_001.json": dataHierarchiesTime_001Json,
	"data/hierarchies.json": dataHierarchiesJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"datasets": &bintree{nil, map[string]*bintree{
			"AF001EW": &bintree{nil, map[string]*bintree{
				"2016": &bintree{nil, map[string]*bintree{
					"1": &bintree{nil, map[string]*bintree{
						"1.json": &bintree{dataDatasetsAf001ew201611Json, map[string]*bintree{}},
						"dimensions.json": &bintree{dataDatasetsAf001ew20161DimensionsJson, map[string]*bintree{}},
					}},
					"versions.json": &bintree{dataDatasetsAf001ew2016VersionsJson, map[string]*bintree{}},
				}},
				"editions.json": &bintree{dataDatasetsAf001ewEditionsJson, map[string]*bintree{}},
			}},
			"CPI15": &bintree{nil, map[string]*bintree{
				"2017": &bintree{nil, map[string]*bintree{
					"1": &bintree{nil, map[string]*bintree{
						"1.json": &bintree{dataDatasetsCpi15201711Json, map[string]*bintree{}},
						"dimensions.json": &bintree{dataDatasetsCpi1520171DimensionsJson, map[string]*bintree{}},
					}},
					"versions.json": &bintree{dataDatasetsCpi152017VersionsJson, map[string]*bintree{}},
				}},
				"editions.json": &bintree{dataDatasetsCpi15EditionsJson, map[string]*bintree{}},
			}},
			"legacy": &bintree{nil, map[string]*bintree{
				"AF001EW.json": &bintree{dataDatasetsLegacyAf001ewJson, map[string]*bintree{}},
				"CPI15.json": &bintree{dataDatasetsLegacyCpi15Json, map[string]*bintree{}},
			}},
		}},
		"datasets.json": &bintree{dataDatasetsJson, map[string]*bintree{}},
		"hierarchies": &bintree{nil, map[string]*bintree{
			"CI_000641.json": &bintree{dataHierarchiesCi_000641Json, map[string]*bintree{}},
			"TIME_001.json": &bintree{dataHierarchiesTime_001Json, map[string]*bintree{}},
		}},
		"hierarchies.json": &bintree{dataHierarchiesJson, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

